("afawk" "as far as we know")
("app" "application")
("dify" "difficulty")
("difys" "difficulties")
("ilu" "illustrate")
("ilus" "illustrates")
("ilud" "illustrated")
("ilug" "illustrating")
("nec" "necessary")
("otoh" "on the other hand")
("popn" "population")
("pov" "point of view")
("rsp" "respective")
("rspy" "respectively")
("suf" "sufficiently")
("trang" "transforming")
("trans" "transformations")
("substn" "substitution")
("substns" "substitutions")
("substd" "substituted")
("st" "such that")
;("ske" "" brac-skel)
