("xx" "" sgml-tag)
("xhead" "" sk_head)
("xbody" "" sk_body)
("xhtml" "" sk_html)
("xtitle" "" sk_title)
("xxbody" "" sk_arg_body)
("xh1" "" sk_h1)
("xh2" "" sk_h2)
("xh3" "" sk_h3)
("xh4" "" sk_h4)
("xh5" "" sk_h5)
("xh6" "" sk_h6)
("ximg" "" sk_img)
("xa" "" sk_a)

("xtest" "" read-two-vars)
