("noof" "number of")
("loln" "law of large numbers")
("sv" "seasonal variation")
("NYC" "New York City")
("NY" "New York")
("US" "United States")
("jandec" "Jan  Feb  Mar  Apr  May  June  July  Aug  Sept  Oct  Nov  Dec")
("cm" "class marks")
("forex" "for example")