("alg" "algebra")
("albc" "algebraic")
("ana" "analytic")
("ap" "arithmetic progression")
("apx" "approximate")
("apxn" "approximation")
("apxy" "approximately")
("apxns" "approximations")
("ari" "arithmetic")
("arim" "arithmetic mean")
("aria" "arithmetic average")
("avg" "average")
("avgs" "averages")
("ber" "Bernouilli")
("bino" "binomial")
("calc" "calculation")
("calcs" "calculations")
("clc" "calculate")
("clcs" "calculates")
("clcg" "calculating")
("clcd" "calculated")
("charc" "characteristic")
("coeff" "coefficient")
("coeffs" "coefficients")
("combn" "combination")
("combns" "combinations")
("corr" "correlation")
("corrd" "correlated")
("cts" "continuous")
("ctsly" "continuously")
("dec" "decrease")
("dcp" "decimal place")
("dcps" "decimal places")
("def" "definition")
("dett" "determinant")
("dev" "deviation")
("devs" "deviations")
("dfn" "differentiation")
("dfbl" "differentiable")
("dist" "distribution")
("dists" "distributions")
("distd" "distributed")
("ebas" "\\brak{\\mathbf{e}_1,\\ \\dots,\\ \\mathbf{e}_n}")
("epbas" "\\brak{\\mathbf{e}\\p{1}_1,\\ \\dots,\\ \\mathbf{e}\\p{1}_n}")
("etbas" "\\brak{\\tilde{\\mathbf{e}}_1,\\ \\dots,\\ \\tilde{\\mathbf{e}}_n}")
("x1xn" "\\brac{x^1,\\dots,x^n}")
("eco" "economics")
("eq" "equation")
("eqbm" "equilibrium")
("eqs" "equations")
("expr" "expression")
("exprs" "expressions")
("fdist" "frequency distribution")
("fdists" "frequency distributions")
("fn" "function")
("fnd" "fundamental")
("Fnd" "Fundamental")
("fns" "functions")
("freq" "frequency")
("freqs" "frequencies")
("fdml" "fundamental")
("gm" "geometric mean")
("gmc" "geometric")
("gp" "geometric progression")
("gt" "greater than")
("ha" "harmonic average")
("htro" "heterogeneous")
("homo" "homogeneous")
("inc" "increase")
("indep" "independent")
("ineq" "inequality")
("ineqs" "inequality")
("inv" "inverse")
("jprob" "joint probability")
("jpdist" "joint probability distribution")
("lg" "logarithm")
("lgs" "logarithms")
("lgmc" "logarithmic")
("lin" "linear")
("lina" "linear algebra")
("lindep" "linearly dependent")
("linidep" "linearly independent")
("lt " "less than")
("msc" "miscallaneous")
("mthl" "mathematical")
("mthly" "mathematically")
("mths" "mathematics")
("muex" "mutually exclusive")
("mxm" "maximum")
("mnm" "minimum")
("nbhd" "neighbourhood")
("nbr" "number")
("nbrs" "numbers")
("nec" "necessary")
("neg" "negative")
("nlin" "non-linear")
("otoh" "on the other hand")
("parb" "parabola")
("parbs" "parabolas")
("parbc" "parabolic")
("pb" "problem")
("pbs" "problems")
("pd" "period")
("pds" "periods")
("pdc" "periodic")
("pdcy" "periodicity")
("pdcs" "periodicities")
("perm" "permutation")
("perms" "permutations")
("poi" "Poisson")
("poid" "Poisson distribution")
("prt" "particular")
("prp" "proposition")
("prty" "particularly")
("poly" "polynomial")
("pos" "positive")
("posn" "position")
("prd" "product")
("prob" "probability")
("probs" "probabilities")
("qfrm" "quadratic form")
("qn" "question")
("qns" "questions")
("qty" "quantity")
("qtys" "quantities")
("rsp" "respective")
("rspy" "respectively")
("sb" "subscript")
("sbs" "subscripts")
("sdev" "standard deviation")
("sdevs" "standard deviations")
("sf" "significant figures")
("sgn" "significant")
("simu" "simultaneous")
("simy" "simultaneously")
("sl" "straight line")
("soln" "solution")
("solns" "solutions")
("sp" "superscript")
("sps" "superscripts")
("st" "such that")
("stat" "statistic")
("statl" "statistical")
("stats" "statistics")
("suf" "sufficient")
("tran" "transformation")
("thm" "theorem")
("thms" "theorems")
("trang" "transforming")
("trans" "transformations")
("uni" "uniform")
("uniy" "uniformly")
("var" "variable")
("vars" "variables")
("vs" "vector space")
("wd" "well defined")
("wrt" "with respect to")
("mvt" "Mean Value Theorem")
